-- Run this once against your Neon database (Neon console -> SQL Editor, or via psql)

create extension if not exists pgcrypto;
create extension if not exists vector;

-- Officials (learners) -----------------------------------------------------
create table if not exists officials (
    id uuid primary key default gen_random_uuid(),
    auth_user_id uuid,                    -- unused in MVP (no real auth -- frontend uses a profile picker instead); kept for future SSO integration
    name text not null,
    designation text,
    department text,
    job_role text,
    education text,
    experience_years numeric,
    past_trainings text[],                -- simple list of past course titles for MVP
    role text default 'learner',          -- 'learner' | 'admin'
    created_at timestamptz default now()
);

-- Competency framework (static reference data, seeded from data/competency_framework.json)
create table if not exists competencies (
    id uuid primary key default gen_random_uuid(),
    domain text not null,                 -- Statistical | Technical | DigitalGovernance | Behavioural
    name text not null unique,            -- e.g. "Survey Design", "Python"
    description text
);

-- Per-official competency scores (0-100), one row per official+competency
create table if not exists competency_scores (
    id uuid primary key default gen_random_uuid(),
    official_id uuid references officials(id) on delete cascade,
    competency_id uuid references competencies(id) on delete cascade,
    score numeric default 0,              -- current level
    target_score numeric default 80,      -- expected level for their role
    updated_at timestamptz default now(),
    unique (official_id, competency_id)
);

-- Courses: unified pool, source distinguishes iGOT vs NSSTA -----------------
create table if not exists courses (
    id uuid primary key default gen_random_uuid(),
    title text not null,
    description text,
    domain text,                          -- matches competencies.domain
    sub_skill text,                       -- matches competencies.name
    level text,                           -- Beginner | Intermediate | Advanced
    duration_hrs numeric,
    source text default 'iGOT',           -- 'iGOT' | 'NSSTA' -- merge point, see recommendation_engine
    url text,                             -- links to the real platform homepage (igotkarmayogi.gov.in / nssta.gov.in)
    embedding vector(384)                 -- sentence-transformers all-MiniLM-L6-v2 dim
);

-- Recommendations shown to an official (generated, cached for dashboard speed)
create table if not exists recommendations (
    id uuid primary key default gen_random_uuid(),
    official_id uuid references officials(id) on delete cascade,
    course_id uuid references courses(id) on delete cascade,
    reason text,                          -- short LLM-generated "why this was recommended"
    score numeric,                        -- similarity/relevance score
    created_at timestamptz default now()
);

-- Uploaded learning materials for quiz generation
create table if not exists learning_materials (
    id uuid primary key default gen_random_uuid(),
    uploaded_by uuid references officials(id) on delete cascade,
    file_name text,
    storage_path text,                    -- unused in MVP (raw file isn't kept, only extracted_text below)
    extracted_text text,
    created_at timestamptz default now()
);

-- Generated quizzes + questions ---------------------------------------------
create table if not exists quizzes (
    id uuid primary key default gen_random_uuid(),
    material_id uuid references learning_materials(id) on delete cascade,
    official_id uuid references officials(id) on delete cascade,   -- who this quiz was personalized for
    title text,
    created_at timestamptz default now()
);

-- Every question now carries WHAT concept it tests and HOW hard it is.
create table if not exists quiz_questions (
    id uuid primary key default gen_random_uuid(),
    quiz_id uuid references quizzes(id) on delete cascade,
    competency_id uuid references competencies(id) on delete cascade,   -- which of the 33 concepts this tests
    difficulty text not null default 'Intermediate',  -- 'Beginner' | 'Intermediate' | 'Advanced'
    is_remedial boolean default false,                -- true if generated by the remediation loop, not the initial batch
    question text,
    options jsonb,                        -- ["A ...", "B ...", "C ...", "D ..."]
    correct_option text,                  -- e.g. "B"
    explanation text,
    created_at timestamptz default now()
);

-- One adaptive session per quiz attempt. Tracks per-concept difficulty state
create table if not exists quiz_sessions (
    id uuid primary key default gen_random_uuid(),
    quiz_id uuid references quizzes(id) on delete cascade,
    official_id uuid references officials(id) on delete cascade,
    concept_state jsonb default '{}',     -- {"<competency_id>": {"difficulty": "Beginner", "consecutive_correct": 0, "mastered": false, "in_remediation": false}}
    queue jsonb default '[]',             -- ordered list of pending quiz_question ids; remedial questions get pushed to the front
    status text default 'in_progress',    -- 'in_progress' | 'completed'
    started_at timestamptz default now(),
    completed_at timestamptz
);

-- Fine-grained per-question attempt log
create table if not exists question_attempts (
    id uuid primary key default gen_random_uuid(),
    session_id uuid references quiz_sessions(id) on delete cascade,
    question_id uuid references quiz_questions(id) on delete cascade,
    official_id uuid references officials(id) on delete cascade,
    competency_id uuid references competencies(id) on delete cascade,
    difficulty text,
    selected_option text,
    is_correct boolean,
    answered_at timestamptz default now()
);

-- Kept for the simple final-score summary shown on the dashboard.
create table if not exists quiz_attempts (
    id uuid primary key default gen_random_uuid(),
    quiz_id uuid references quizzes(id) on delete cascade,
    session_id uuid references quiz_sessions(id) on delete set null,
    official_id uuid references officials(id) on delete cascade,
    score numeric,
    total numeric,
    concepts_mastered text[],             -- competency names that reached mastery this session
    concepts_needing_practice text[],     -- competency names that stayed weak
    taken_at timestamptz default now()
);

-- Index for vector similarity search on courses (using HNSW for empty-table compatibility)
create index if not exists courses_embedding_hnsw_idx on courses using hnsw (embedding vector_cosine_ops);
